package uncc2014watsonsim;

public enum Score {
	INDRI_RANK,
	INDRI_SCORE,
	LUCENE_RANK,
	LUCENE_SCORE,
	GOOGLE_RANK,
	BING_RANK,
	INDRI_PASSAGE_RETRIEVAL_RANK,
	INDRI_PASSAGE_RETRIEVAL_SCORE,
	WORD_PROXIMITY,
	COMBINED,
	CORRECT,
	GARBAGE,
	TEST_SCORER_SS
}
